server:
  port: 8083
spring:
  application:
    name: provider-umc-api
  main:
    allow-bean-definition-overriding: true
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:8761/eureka
